version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: onlyoneFrontend
    ports:
      - 8888:80
  back:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
  
