name: backend
on:
  pull_request:
    types: [opened, synchronize]
    branches:
    - main
jobs:
  build:
    if: contains(github.head_ref, '_back_') || contains(github.head_ref, '_backend_')
    runs-on: ubuntu-latest
    steps:
    - name: install gcloud 
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Set credentials file to home directory
      run: echo ${{ secrets.GOOGLE_CREDS_JSON}} > ~/service-account.json
    - name: install emulator dep
      run: sudo apt-get install -y openjdk-8-jre 
    - name: install beta cmd
      run: gcloud --quiet components install beta cloud-firestore-emulator
    - name: launch emulator
      run: gcloud --quiet beta emulators firestore start --host-port=localhost &
    - name: wait for emulator
      run: sleep 7
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      working-directory: ./backend 
      run: go build -v ./...

    - name: Test
      working-directory: ./backend
      run: go test -v ./...
