name: backend

on:
  push:
    branches: [ "main" , "feature_cicd_golang"]
  pull_request:
    branches: [ "main", "feat*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install gcloud deps
      run: sudo apt-get install -y apt-transport-https ca-certificates gnupg
    - name: install gcloud 
      run: sudo echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && sudo curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && sudo apt-get update -y && sudo apt-get install google-cloud-cli -y
    
    - name: Set credentials file to home directory
      run: echo ${{ secrets.GOOGLE_CREDS_JSON}} > ~/service-account.json
    - name: install emulator dep
      run: sudo apt-get install -y openjdk-8-jre 
    - name: launch emulator
      run: gcloud beta emulators firestore start --host-port=localhost &
    - name: wait for emulator
      run: sleep 7
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      working-directory: ./backend 
      run: go build -v ./...

    - name: Test
      working-directory: ./backend
      run: go test -v ./...
