name: frontend

on:
  push:
    branches: [ "feat_frontend_cicd"]
  pull_request:
    branches: [ "main", "feat*" ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v2

    - name: Install npm packages
      run: cd frontend && npm install

    - name: Build Angular app
      run: cd frontend && npm run build

    - name: Debug 
      run: cd frontend && ls

    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: git push origin `git subtree split --prefix frontend/dist master`:gh-pages --force

