name: frontend

on:
  pull_request:
    branches: 
      - main

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    if: contains(github.head_ref, '_front_') || contains(github.head_ref, '_frontend_')
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v3

    - name: Install npm packages
      run: cd frontend && npm ci

    - name: Build and test Angular app
      run: cd frontend && npm run test:prod